import Link from "next/link";
import { siteConfig } from "@/config/site";

export const metadata = {
  title: "Terms of Service",
  description: "CareerForgeX Terms of Service governing website access and system implementation engagements.",
};

export default function TermsPage() {
  return (
    <div className="py-16 lg:py-24 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8 text-xs sm:text-sm text-gray-300 leading-relaxed">
      <div className="border-b border-dark-border pb-6 space-y-2">
        <h1 className="text-3xl sm:text-4xl font-extrabold text-white">Terms of Service</h1>
        <p className="text-xs text-gray-500 font-mono">Effective Date: September 2026</p>
      </div>

      <div className="p-4 rounded-xl bg-dark-card border border-dark-border text-xs text-gray-400 italic">
        Disclaimer: This website does not provide legal advice. The terms herein define acceptable usage and service scopes.
      </div>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white">1. Acceptance of Terms</h2>
        <p>
          By accessing the CareerForgeX website, testing interactive demos, or submitting business details for scoping,
          you agree to be bound by these Terms of Service and our Privacy Policy.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white">2. Scope of Services & Scoping Engagements</h2>
        <p>
          CareerForgeX provides custom AI automation design, workflow integration, agent development, and systems consulting.
          Individual customer deployments are governed by mutually executed Statements of Work (SOW) defining milestones,
          acceptance criteria, and specific deliverables.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white">3. Interactive Demos & Non-Guaranteed Estimates</h2>
        <p>
          Calculations generated by the Labor Capacity & ROI Estimator and outputs produced by the Interactive Playground
          are simulated demonstrations based on user inputs. They do not constitute guaranteed financial returns,
          contractual warranties, or legal commitments.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white">4. Intellectual Property</h2>
        <p>
          Under our standard client agreements, clients retain full ownership of their pre-existing proprietary data,
          custom workflows, and dedicated models upon project completion. CareerForgeX retains rights to its underlying
          generic orchestration libraries and reusable tool connectors.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white">5. Acceptable Use Policy</h2>
        <p>
          You agree not to use our interactive playground or APIs to transmit malicious payloads, perform denial-of-service
          attacks, or process illegal, infringing, or harmful materials.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white">6. Contact Information</h2>
        <p>
          For contractual inquiries, reach out to{" "}
          <a href={`mailto:${siteConfig.contact.email}`} className="text-brand-400 hover:underline">
            {siteConfig.contact.email}
          </a>.
        </p>
      </section>
    </div>
  );
}
